### ISSUE TITLE
Let the client to list child navigation can be harmful?

### ISSUE THREAD

**Issue by mar9000** [metadevpro/cal#6]
In https://github.com/metadevpro/cal/blob/master/cal.md#cal-5-projection the client can request also the list of child associations to navigate. That's something that GraphQL implements but in case the backend has a SQL database it could generate very complex query.

**Comment by pjmolina** [comment]
Indeed! 
CAL recommendations should be seen like optional capabilities.
Is up to the server implementation to decide where this capability is implemented or not. 
For example, a server can return `501 Not Implemented`.

**Comment by mar9000** [comment]
That's reasonable. Then with respect to projections I would suggest to add (somewhere) something like `projection=<projection name>` in case one wants an API with a stronger semantic. In this case the API could also return the list of the available projections.
